spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/${db}?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${user}
    password: ${pw}


jwt:
  secret: ${key}
  access-expiration-time: 7200000 # 2시간 (밀리초)
  refresh-expiration-time: 86400000 # 24시간 (밀리초)